import {
  FileType2,
  FileSpreadsheet,
  Presentation,
  Image as ImageIcon,
  PenTool,
  FileText,
  BookOpen,
  Apple,
  Newspaper,
  Stethoscope,
  FileImage,
  Images,
  FileCheck2,
  Combine,
  Scissors,
  Lock,
  KeyRound,
  Highlighter,
  FileDown,
  Minimize2,
  XCircle,
  RotateCw,
  Layers,
  Wrench,
  Printer,
  type LucideIcon,
} from "lucide-react";

export type Tool = {
  slug: string;
  name: string;
  icon: LucideIcon;
  tint: string;
  accent: string;
  from: string;
  to: string;
  headline: string;
  description: string;
};

export const tools: Tool[] = [
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    icon: FileType2,
    tint: "tint-blue",
    accent: "accent-blue",
    from: "Word",
    to: "PDF",
    headline: "Word to PDF Converter",
    description: "Convert DOC and DOCX files to PDF in seconds, with layout and fonts intact.",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    icon: FileSpreadsheet,
    tint: "tint-green",
    accent: "accent-green",
    from: "Excel",
    to: "PDF",
    headline: "Excel to PDF Converter",
    description: "Turn XLS and XLSX spreadsheets into clean, shareable PDF documents.",
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    icon: Presentation,
    tint: "tint-orange",
    accent: "accent-orange",
    from: "PowerPoint",
    to: "PDF",
    headline: "PowerPoint to PDF Converter",
    description: "Convert PPT and PPTX slide decks to PDF for easy sharing and printing.",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    icon: ImageIcon,
    tint: "tint-violet",
    accent: "accent-violet",
    from: "JPG",
    to: "PDF",
    headline: "JPG to PDF Converter",
    description: "Combine JPG and JPEG images into a single high quality PDF file.",
  },
  {
    slug: "autocad-to-pdf",
    name: "AutoCAD to PDF",
    icon: PenTool,
    tint: "tint-red",
    accent: "accent-red",
    from: "AutoCAD",
    to: "PDF",
    headline: "AutoCAD to PDF Converter",
    description: "Convert DWG and DXF drawings to PDF while keeping every line crisp.",
  },
  {
    slug: "openoffice-to-pdf",
    name: "OpenOffice to PDF",
    icon: FileText,
    tint: "tint-blue",
    accent: "accent-blue",
    from: "OpenOffice",
    to: "PDF",
    headline: "OpenOffice to PDF Converter",
    description: "Convert ODT, ODS and ODP documents to PDF in a couple of clicks.",
  },
  {
    slug: "ebooks-to-pdf",
    name: "eBooks to PDF",
    icon: BookOpen,
    tint: "tint-orange",
    accent: "accent-orange",
    from: "eBook",
    to: "PDF",
    headline: "eBooks to PDF Converter",
    description: "Convert EPUB and MOBI eBooks to PDF so you can read them anywhere.",
  },
  {
    slug: "iwork-to-pdf",
    name: "iWork to PDF",
    icon: Apple,
    tint: "tint-slate",
    accent: "accent-slate",
    from: "iWork",
    to: "PDF",
    headline: "iWork to PDF Converter",
    description: "Convert Pages, Numbers and Keynote files to PDF without a Mac.",
  },
  {
    slug: "publisher-to-pdf",
    name: "Publisher to PDF",
    icon: Newspaper,
    tint: "tint-green",
    accent: "accent-green",
    from: "Publisher",
    to: "PDF",
    headline: "Publisher to PDF Converter",
    description: "Convert Microsoft Publisher PUB files to print ready PDF documents.",
  },
  {
    slug: "dicom-to-pdf",
    name: "DICOM to PDF",
    icon: Stethoscope,
    tint: "tint-teal",
    accent: "accent-teal",
    from: "DICOM",
    to: "PDF",
    headline: "DICOM to PDF Converter",
    description: "Convert medical DICOM images to PDF for reporting and easy sharing.",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    icon: FileType2,
    tint: "tint-blue",
    accent: "accent-blue",
    from: "PDF",
    to: "Word",
    headline: "PDF to Word Converter",
    description:
      "Convert your PDF to an editable Word document. Formatting, tables and images stay exactly where they belong.",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    icon: FileSpreadsheet,
    tint: "tint-green",
    accent: "accent-green",
    from: "PDF",
    to: "Excel",
    headline: "PDF to Excel Converter",
    description: "Pull tables out of any PDF into an editable Excel spreadsheet.",
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to Powerpoint",
    icon: Presentation,
    tint: "tint-orange",
    accent: "accent-orange",
    from: "PDF",
    to: "PowerPoint",
    headline: "PDF to PowerPoint Converter",
    description: "Turn PDF pages into editable PowerPoint slides in seconds.",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    icon: FileImage,
    tint: "tint-violet",
    accent: "accent-violet",
    from: "PDF",
    to: "JPG",
    headline: "PDF to JPG Converter",
    description: "Export every page of your PDF as a high resolution JPG image.",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    icon: FileImage,
    tint: "tint-violet",
    accent: "accent-violet",
    from: "PDF",
    to: "PNG",
    headline: "PDF to PNG Converter",
    description: "Convert PDF pages to sharp PNG images with transparent support.",
  },
  {
    slug: "extract-pdf-images",
    name: "Extract PDF Images",
    icon: Images,
    tint: "tint-violet",
    accent: "accent-violet",
    from: "PDF",
    to: "Images",
    headline: "Extract Images from PDF",
    description: "Pull every embedded image out of a PDF at original quality.",
  },
  {
    slug: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    icon: FileCheck2,
    tint: "tint-blue",
    accent: "accent-blue",
    from: "PDF",
    to: "PDF/A",
    headline: "PDF to PDF/A Converter",
    description: "Convert PDF files to the PDF/A archival standard for long term storage.",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    icon: Combine,
    tint: "tint-orange",
    accent: "accent-orange",
    from: "PDFs",
    to: "one PDF",
    headline: "Merge PDF Files",
    description: "Combine several PDFs into one document, in the order you choose.",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    icon: Scissors,
    tint: "tint-orange",
    accent: "accent-orange",
    from: "PDF",
    to: "pages",
    headline: "Split PDF",
    description: "Split a PDF into separate files by page range or single pages.",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    icon: Lock,
    tint: "tint-teal",
    accent: "accent-teal",
    from: "PDF",
    to: "protected PDF",
    headline: "Protect PDF with a Password",
    description: "Add a password and encryption to keep your PDF documents private.",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    icon: KeyRound,
    tint: "tint-teal",
    accent: "accent-teal",
    from: "locked PDF",
    to: "PDF",
    headline: "Unlock PDF",
    description: "Remove passwords and restrictions from PDFs you own.",
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    icon: Highlighter,
    tint: "tint-teal",
    accent: "accent-teal",
    from: "PDF",
    to: "redacted PDF",
    headline: "Redact PDF",
    description: "Permanently black out sensitive text and images inside a PDF.",
  },
  {
    slug: "pdf-converter",
    name: "PDF Converter",
    icon: FileDown,
    tint: "tint-red",
    accent: "accent-red",
    from: "any file",
    to: "PDF",
    headline: "Online PDF Converter",
    description: "Easily convert to and from PDF in seconds.",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    icon: Minimize2,
    tint: "tint-red",
    accent: "accent-red",
    from: "PDF",
    to: "smaller PDF",
    headline: "Compress PDF",
    description: "Shrink PDF file size while keeping your documents readable.",
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    icon: XCircle,
    tint: "tint-red",
    accent: "accent-red",
    from: "PDF",
    to: "trimmed PDF",
    headline: "Delete Pages from PDF",
    description: "Remove the pages you don't need and download a clean PDF.",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    icon: RotateCw,
    tint: "tint-red",
    accent: "accent-red",
    from: "PDF",
    to: "rotated PDF",
    headline: "Rotate PDF Pages",
    description: "Rotate single pages or the whole document and save it permanently.",
  },
  {
    slug: "flatten-pdf",
    name: "Flatten PDF",
    icon: Layers,
    tint: "tint-red",
    accent: "accent-red",
    from: "PDF",
    to: "flattened PDF",
    headline: "Flatten PDF",
    description: "Flatten form fields, annotations and layers into static content.",
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    icon: Wrench,
    tint: "tint-red",
    accent: "accent-red",
    from: "damaged PDF",
    to: "PDF",
    headline: "Repair PDF",
    description: "Recover data from corrupted or damaged PDF files.",
  },
  {
    slug: "print-ready-pdf",
    name: "Print-Ready PDF",
    icon: Printer,
    tint: "tint-red",
    accent: "accent-red",
    from: "PDF",
    to: "print-ready PDF",
    headline: "Print-Ready PDF",
    description: "Prepare a PDF for professional printing with the right settings.",
  },
];

export const toolBySlug = (slug: string) => tools.find((t) => t.slug === slug);

export const navTools = [
  { slug: "pdf-converter", label: "Convert" },
  { slug: "merge-pdf", label: "Merge" },
  { slug: "split-pdf", label: "Split" },
  { slug: "protect-pdf", label: "Protect" },
  { slug: "unlock-pdf", label: "Unlock" },
  { slug: "compress-pdf", label: "Compress" },
  { slug: "rotate-pdf", label: "Rotate" },
  { slug: "redact-pdf", label: "Redact" },
  { slug: "flatten-pdf", label: "Flatten" },
];
